# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [_dev1]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
#       - name: setup python
#         uses: actions/setup-python@v2
#         with:
#           python-version: "3.x"
#       - name: install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install requests
      - name: exec test
        run: cat targets.txt | python3 test.py
        # working-directory: ./ansible
